# Generated by Django 4.1.1 on 2022-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_todo_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(default="url"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="firstname",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastname",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=128),
        ),
    ]
