# Generated by Django 4.1.1 on 2022-10-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_project_url_alter_user_email_alter_user_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.project",
            ),
        ),
    ]
