# Generated by Django 4.1.1 on 2022-10-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_todo_created_todo_is_active_todo_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
