# Generated by Django 4.1.1 on 2022-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_project_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="project",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
        migrations.AddField(
            model_name="todo",
            name="project",
            field=models.ManyToManyField(to="users.project"),
        ),
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ManyToManyField(to="users.user"),
        ),
    ]
