# Generated by Django 4.1.1 on 2022-11-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_todo_project_todo_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
        migrations.AddField(
            model_name="todo",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
