# Generated by Django 4.1.1 on 2022-11-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="author",
            new_name="user",
        ),
    ]
